<?php

use XOzymandias\Yii2Postal\models\ShipmentDirectionInterface;
use XOzymandias\Yii2Postal\models\ShipmentProviderInterface;
use yii\db\Expression;

return [
	'shipment_in_PP' => [
		'id' => 1,
		'number' => 'RR123456789PL',
		'guid' => 'guid-abc-123',
		'buffer_id' => 12,
		'provider' => ShipmentProviderInterface::PROVIDER_POCZTA_POLSKA,
		'direction' => ShipmentDirectionInterface::DIRECTION_IN,
		'content_id' => 1,
		'creator_id' => 2,
		'created_at' => new Expression('Now()'),
		'updated_at' => new Expression('Now()'),
		'finished_at' => null,
		'shipment_at' => null,
		'api_data' => null,
	],
	'shipment_out_PP' => [
		'id' => 2,
		'number' => '',
		'guid' => 'guid-abc-123',
		'buffer_id' => 13,
		'provider' => ShipmentProviderInterface::PROVIDER_POCZTA_POLSKA,
		'direction' => ShipmentDirectionInterface::DIRECTION_OUT,
		'content_id' => 1,
		'creator_id' => 2,
		'created_at' => new Expression('Now() - INTERVAL 7 DAY'),
		'updated_at' => new Expression('Now() - INTERVAL 7 DAY'),
		'finished_at' => new Expression('Now() + INTERVAL 7 DAY'),
		'shipment_at' => new Expression('Now() + INTERVAL 7 DAY'),
		'api_data' => null,
	],
	[
		'id' => 3,
		'number' => '',
		'guid' => 'guid-abc-223',
		'buffer_id' => 3,
		'provider' => ShipmentProviderInterface::PROVIDER_POCZTA_POLSKA,
		'direction' => ShipmentDirectionInterface::DIRECTION_OUT,
		'content_id' => 1,
		'creator_id' => 2,
		'created_at' => new Expression('Now() - INTERVAL 4 DAY'),
		'updated_at' => new Expression('Now() - INTERVAL 4 DAY'),
		'finished_at' => null,
		'shipment_at' => null,
		'api_data' => null,
	],
	[
		'id' => 4,
		'number' => '',
		'guid' => 'guid-abc-223',
		'buffer_id' => 3,
		'provider' => ShipmentProviderInterface::PROVIDER_POCZTA_POLSKA,
		'direction' => ShipmentDirectionInterface::DIRECTION_IN,
		'content_id' => 1,
		'creator_id' => 2,
		'created_at' => new Expression('Now() - INTERVAL 17 DAY'),
		'updated_at' => new Expression('Now() - INTERVAL 17 DAY'),
		'finished_at' => new Expression('Now() + INTERVAL 17 DAY'),
		'shipment_at' => new Expression('Now() + INTERVAL 17 DAY'),
		'api_data' => null,
	],
	[
		'id' => 5,
		'number' => '',
		'guid' => 'guid-xyz-101',
		'buffer_id' => 4,
		'provider' => ShipmentProviderInterface::PROVIDER_POCZTA_POLSKA,
		'direction' => ShipmentDirectionInterface::DIRECTION_OUT,
		'content_id' => 2,
		'creator_id' => 3,
		'created_at' => new Expression('Now() - INTERVAL 2 DAY'),
		'updated_at' => new Expression('Now() - INTERVAL 2 DAY'),
		'finished_at' => null,
		'shipment_at' => new Expression('Now() - INTERVAL 1 DAY'),
		'api_data' => null,
	],
	[
		'id' => 6,
		'number' => '',
		'guid' => 'guid-lmn-778',
		'buffer_id' => 5,
		'provider' => ShipmentProviderInterface::PROVIDER_POCZTA_POLSKA,
		'direction' => ShipmentDirectionInterface::DIRECTION_IN,
		'content_id' => 3,
		'creator_id' => 1,
		'created_at' => new Expression('Now() - INTERVAL 10 DAY'),
		'updated_at' => new Expression('Now() - INTERVAL 10 DAY'),
		'finished_at' => new Expression('Now() - INTERVAL 2 DAY'),
		'shipment_at' => new Expression('Now() - INTERVAL 3 DAY'),
		'api_data' => null,
	],
	[
		'id' => 7,
		'number' => '',
		'guid' => 'guid-opq-912',
		'buffer_id' => 5,
		'provider' => ShipmentProviderInterface::PROVIDER_POCZTA_POLSKA,
		'direction' => ShipmentDirectionInterface::DIRECTION_OUT,
		'content_id' => 2,
		'creator_id' => 2,
		'created_at' => new Expression('Now() - INTERVAL 20 DAY'),
		'updated_at' => new Expression('Now() - INTERVAL 20 DAY'),
		'finished_at' => new Expression('Now() - INTERVAL 10 DAY'),
		'shipment_at' => new Expression('Now() - INTERVAL 12 DAY'),
		'api_data' => null,
	],
	[
		'id' => 8,
		'number' => '',
		'guid' => 'guid-rst-456',
		'buffer_id' => 6,
		'provider' => ShipmentProviderInterface::PROVIDER_POCZTA_POLSKA,
		'direction' => ShipmentDirectionInterface::DIRECTION_IN,
		'content_id' => 4,
		'creator_id' => 3,
		'created_at' => new Expression('Now() - INTERVAL 1 DAY'),
		'updated_at' => new Expression('Now() - INTERVAL 1 DAY'),
		'finished_at' => null,
		'shipment_at' => null,
		'api_data' => null,
	],
	[
		'id' => 9,
		'number' => '',
		'guid' => 'guid-uvw-555',
		'buffer_id' => 7,
		'provider' => ShipmentProviderInterface::PROVIDER_POCZTA_POLSKA,
		'direction' => ShipmentDirectionInterface::DIRECTION_OUT,
		'content_id' => 1,
		'creator_id' => 2,
		'created_at' => new Expression('Now() - INTERVAL 30 DAY'),
		'updated_at' => new Expression('Now() - INTERVAL 30 DAY'),
		'finished_at' => new Expression('Now() - INTERVAL 25 DAY'),
		'shipment_at' => new Expression('Now() - INTERVAL 28 DAY'),
		'api_data' => null,
	],
];