<?php

use XOzymandias\Yii2Postal\models\ShipmentAddress;

return [
    'sender' => [
        'id' => 1,
        'name' => 'Jan Kowalski',
        'postal_code' => '00123',
        'city' => 'Warszawa',
        'country' => 'PL',
        'default_role' => ShipmentAddress::ROLE_SENDER,
        'city_id' => 101,
        'street' => 'Marszałkowska',
        'apartment_number' => '5',
        'house_number' => '12A',
        'name_2' => 'Biuro',
        'phone' => '123456789',
        'mobile' => '987654321',
        'contact_person' => '123456789',
        'email' => 'jan@example.com',
        'taxID' => '1234567890',
    ],
    'receiver' => [
        'id' => 2,
        'name' => 'Marek Nowak',
        'postal_code' => '33210',
        'city' => 'Kraków',
        'country' => 'PL',
        'default_role' => ShipmentAddress::ROLE_RECEIVER,
        'city_id' => 101,
        'street' => 'Piastowska',
        'apartment_number' => '1',
        'house_number' => '1',
        'name_2' => 'Zakład',
        'phone' => '123456789',
        'mobile' => '987654321',
        'contact_person' => '123456789',
        'email' => 'kowal@example.com',
        'taxID' => '1234567890',
    ],
    'both' => [
        'id' => 3,
        'name' => 'Tom Johnson',
        'postal_code' => '34310',
        'city' => 'New York',
        'country' => 'US',
        'default_role' => ShipmentAddress::ROLE_BOTH,
        'city_id' => 101,
        'street' => 'Jenkins',
        'apartment_number' => '1',
        'house_number' => '1',
        'name_2' => 'Office',
        'phone' => '124351789',
        'mobile' => '987604321',
        'contact_person' => '023456780',
        'email' => 'john@snow.com',
        'taxID' => '1234167890',
    ],
    'address_only_required' => [
        'id' => 4,
        'name' => 'Marek Krwawdoń',
        'house_number' => '8',
        'postal_code' => '54321',
        'city' => 'Kraków',
        'country' => 'PL',
        'city_id' => null,
        'street' => null,
        'apartment_number' => null,
        'name_2' => null,
        'phone' => null,
        'mobile' => null,
        'contact_person' => null,
        'email' => null,
        'taxID' => null,
    ],
    [
        'id' => 5,
        'name' => 'Jan Kowalski',
        'postal_code' => '31210',
        'city' => 'Kraków',
        'country' => 'PL',
        'city_id' => 101,
        'street' => 'Chrobrzysta',
        'apartment_number' => '1',
        'house_number' => '1',
        'name_2' => 'Zakład',
        'phone' => '123456789',
        'mobile' => '987654321',
        'contact_person' => '123456789',
        'email' => 'kowal@example.com',
        'taxID' => '1234567890',
    ],
];
