<?php

use XOzymandias\Yii2Postal\models\ShipmentAddress;

return [
    'sender' => [
        'id' => 1,
        'name' => 'Jan Kowalski',
        'postal_code' => '00123',
        'city' => 'Warszawa',
        'country' => 'PL',
        'default_role' => ShipmentAddress::ROLE_SENDER,
        'city_id' => 101,
        'street' => 'Marszałkowska',
        'apartment_number' => '5',
        'house_number' => '12A',
        'name_2' => 'Biuro',
        'phone' => '123456789',
        'mobile' => '987654321',
        'contact_person' => '123456789',
        'email' => 'jan@example.com',
        'taxID' => '1234567890',
    ],
    'receiver' => [
        'id' => 2,
        'name' => 'Marek Nowak',
        'postal_code' => '33210',
        'city' => 'Kraków',
        'country' => 'PL',
        'default_role' => ShipmentAddress::ROLE_RECEIVER,
        'city_id' => 101,
        'street' => 'Piastowska',
        'apartment_number' => '1',
        'house_number' => '1',
        'name_2' => 'Zakład',
        'phone' => '123456789',
        'mobile' => '987654321',
        'contact_person' => '123456789',
        'email' => 'kowal@example.com',
        'taxID' => '1234567890',
    ],
    'both' => [
        'id' => 3,
        'name' => 'Tom Johnson',
        'postal_code' => '34310',
        'city' => 'New York',
        'country' => 'US',
        'default_role' => ShipmentAddress::ROLE_BOTH,
        'city_id' => 101,
        'street' => 'Jenkins',
        'apartment_number' => '1',
        'house_number' => '1',
        'name_2' => 'Office',
        'phone' => '124351789',
        'mobile' => '987604321',
        'contact_person' => '023456780',
        'email' => 'john@snow.com',
        'taxID' => '1234167890',
    ],
    'address_only_required' => [
        'id' => 4,
        'name' => 'Marek Krwawdoń',
        'house_number' => '8',
        'postal_code' => '54321',
        'city' => 'Kraków',
        'country' => 'PL',
        'city_id' => null,
        'street' => null,
        'apartment_number' => null,
        'name_2' => null,
        'phone' => null,
        'mobile' => null,
        'contact_person' => null,
        'email' => null,
        'taxID' => null,
    ],
    [
        'id' => 5,
        'name' => 'Jan Kowalski',
        'postal_code' => '31210',
        'city' => 'Kraków',
        'country' => 'PL',
        'city_id' => 101,
        'street' => 'Chrobrzysta',
        'apartment_number' => '1',
        'house_number' => '1',
        'name_2' => 'Zakład',
        'phone' => '123456789',
        'mobile' => '987654321',
        'contact_person' => '123456789',
        'email' => 'kowal@example.com',
        'taxID' => '1234567890',
    ],
	[
		'id' => 6,
		'name' => 'Anna Zielińska',
		'postal_code' => '90210',
		'city' => 'Łódź',
		'country' => 'PL',
		'default_role' => ShipmentAddress::ROLE_RECEIVER,
		'city_id' => 102,
		'street' => 'Kościuszki',
		'apartment_number' => '7',
		'house_number' => '21',
		'name_2' => 'Magazyn',
		'phone' => '222333444',
		'mobile' => '600700800',
		'contact_person' => 'Anna Z.',
		'email' => 'anna.z@example.com',
		'taxID' => '9876543210',
	],
	[
		'id' => 7,
		'name' => 'Robert Lewandowski',
		'postal_code' => '00100',
		'city' => 'Warszawa',
		'country' => 'PL',
		'default_role' => ShipmentAddress::ROLE_SENDER,
		'city_id' => 103,
		'street' => 'Sportowa',
		'apartment_number' => '3',
		'house_number' => '9B',
		'name_2' => 'Biuro klubowe',
		'phone' => '555444333',
		'mobile' => '888777666',
		'contact_person' => 'R. Lewandowski',
		'email' => 'robert@example.com',
		'taxID' => '1122334455',
	],
	[
		'id' => 8,
		'name' => 'Elżbieta Nowicka',
		'postal_code' => '50222',
		'city' => 'Wrocław',
		'country' => 'PL',
		'default_role' => ShipmentAddress::ROLE_BOTH,
		'city_id' => 104,
		'street' => 'Słoneczna',
		'apartment_number' => '14',
		'house_number' => '7',
		'name_2' => 'Salon firmowy',
		'phone' => '111222333',
		'mobile' => '999888777',
		'contact_person' => 'E. Nowicka',
		'email' => 'elzbieta@example.com',
		'taxID' => '2233445566',
	],
	[
		'id' => 9,
		'name' => 'Michael Thompson',
		'postal_code' => '10001',
		'city' => 'New York',
		'country' => 'US',
		'default_role' => ShipmentAddress::ROLE_SENDER,
		'city_id' => 105,
		'street' => '5th Avenue',
		'apartment_number' => '20',
		'house_number' => '501',
		'name_2' => 'Main Office',
		'phone' => '12125551234',
		'mobile' => '12125557654',
		'contact_person' => 'M. Thompson',
		'email' => 'michael.t@example.com',
		'taxID' => '9988776655',
	],
	[
		'id' => 10,
		'name' => 'Hans Müller',
		'postal_code' => '80331',
		'city' => 'München',
		'country' => 'DE',
		'default_role' => ShipmentAddress::ROLE_RECEIVER,
		'city_id' => 106,
		'street' => 'Bahnhofstraße',
		'apartment_number' => '2',
		'house_number' => '4',
		'name_2' => 'Werkstatt',
		'phone' => '49891234567',
		'mobile' => '4915123456789',
		'contact_person' => 'H. Müller',
		'email' => 'hans.mueller@example.de',
		'taxID' => '5566778899',
	],
];
